# Auto-generated by tools/bata/generate_duca_unified_fullmatrix.py.

# Source: docs/experiments/duca_unified_matrix_manifest.yaml

_base_ = ['../e2e_thumos_videomae_s_768x1_160_adapter.py']

matrix_id = 'DUCA-UNIFIED-FULLMATRIX-v001-20260902'

matrix_index = 5

matrix_phase = 'development'

arm_id = 'A11'

seed = 3407

window_size = 768

dense_window_size = 768

selected_budget = 384

scaffold_budget = 128

burst_budget = 256

chunk_num = 24

max_successful_updates = 6000

terminal_epoch_zero_based = 59

terminal_state_key = 'state_dict_ema'

duca_unified_arm = {'id': 'A11',
 'panel': 'prior_x_allocation',
 'prior': 'semantic',
 'allocation': 'robust_phase',
 'curvature': False,
 'quota': 'adaptive',
 'physical_time': False,
 'attribution': 'baseline',
 'mod': False,
 'schedule': 'default_20_20_20',
 'role': 'primary_dense_candidate'}

duca_unified_contract = {'exact_k': True,
 'selected_frames': 384,
 'input_frames': 768,
 'successful_optimizer_updates': 6000,
 'validation_best_checkpoint_forbidden': True,
 'map_to_original_time_before_nms': True}

duca_taylor_attribution = {'enabled': False,
 'feature_levels': ['P0', 'P1'],
 'formula': 'relu(-(detached_gradient * detached_feature).sum(channel))',
 'update_period_successful_steps': 4,
 'target_ema': True,
 'create_graph': False,
 'retain_graph': True}

model = {'type': 'ActionFormer',
 'frame_selector': {'type': 'DucaOnlineFrameSelector',
                    'in_channels': 3,
                    'budget': 384,
                    'budget_mode': 'fixed',
                    'budget_min': 384,
                    'budget_max': 384,
                    'budget_multiple': 16,
                    'target_budget': 384.0,
                    'max_radius': 16,
                    'dense_window_size': 768,
                    'selector_hidden_channels': 96,
                    'actionness_source_cfg': {'type': 'C3CoarseProbeActionnessSource',
                                              'probe_model': 'official-action-seg',
                                              'official_action_seg_backend': 'official_asformer',
                                              'official_num_layers': 2,
                                              'spatial_size': 64,
                                              'tcn_hidden_dim': 96,
                                              'dropout': 0.0,
                                              'frozen': False,
                                              'trainable': True,
                                              'require_checkpoint': False,
                                              'train_split_supervised': True,
                                              'calibration_split': 'train_only',
                                              'thumos_trained': False,
                                              'uses_labels': False,
                                              'uses_teacher': False,
                                              'uses_gt': False,
                                              'uses_prediction_cache': False,
                                              'source_name': 'duca_semantic_asformer_pre_sigmoid_online'},
                    'acquisition_policy': 'robust_phase',
                    'phase_quota_mode': 'adaptive',
                    'phase_sigmas': (1.5, 3.0),
                    'phase_aggregate': 'median',
                    'phase_use_curvature': False,
                    'phase_temporal_nms_radius': 1,
                    'phase_curvature_weight': 0.05,
                    'legacy_scaffold_budget': 128,
                    'legacy_burst_budget': 256,
                    'legacy_burst_radius': 2,
                    'coordinate_space': 'original_time',
                    'detector_output_coordinate_space': 'selected_axis',
                    'selected_positions_unit': 'original_time_index',
                    'true_time_source_axis': 'true_time_dense_index',
                    'detector_gradient_mode': 'st_sparse_gather',
                    'loss_weights': {'actionness': 0.05,
                                     'boundary': 0.25,
                                     'hole': 0.25,
                                     'redundancy': 0.05,
                                     'coverage': 0.05,
                                     'entropy': 0.01,
                                     'teacher': 0.0,
                                     'detector_utility': 0.0},
                    'loss_weight_schedule': {'type': 'progressive_joint',
                                             'warmup_steps': 2000,
                                             'transition_steps': 2000,
                                             'shape': 'cosine',
                                             'detector_utility': {'start': 0.0, 'end': 0.0},
                                             'actionness': {'start': 0.1, 'end': 0.05}},
                    'no_ledger_decision': True,
                    'remap_gt_to_selected_axis': True,
                    'selected_axis_remap_required': True,
                    'forbid_ledger': True,
                    'forbid_raw_prediction_cache': True,
                    'forbid_external_actionness': True,
                    'profile_runtime': True,
                    'profile_sync_cuda': False,
                    'use_coarse_hidden_features': True,
                    'require_coarse_hidden_features': True,
                    'coarse_hidden_dim': 96,
                    'coarse_hidden_proj_dim': 32,
                    'coarse_hidden_dropout': 0.0},
 'backbone': {'backbone': {'total_frames': 16,
                           'ct_tubelet': False,
                           'amod_config': {'enabled': False,
                                           'capacity': 0.65,
                                           'capacity_schedule_successful_steps': [{'start': 0,
                                                                                   'end': 1500,
                                                                                   'start_value': 1.0,
                                                                                   'end_value': 1.0},
                                                                                  {'start': 1500,
                                                                                   'end': 3500,
                                                                                   'start_value': 1.0,
                                                                                   'end_value': 0.75,
                                                                                   'interpolation': 'cosine'},
                                                                                  {'start': 3500,
                                                                                   'end': 5000,
                                                                                   'start_value': 0.75,
                                                                                   'end_value': 0.65,
                                                                                   'interpolation': 'cosine'},
                                                                                  {'start': 5000,
                                                                                   'end': 6000,
                                                                                   'start_value': 0.65,
                                                                                   'end_value': 0.65}],
                                           'amod_layers': [1, 3, 5, 7, 9, 11],
                                           'boundary_prior_scale': 0.25,
                                           'route_temperature': 1.0,
                                           'dense_companion_period_successful_steps': 8}},
              'custom': {'strict_temporal_padding_mask': True,
                         'pre_processing_pipeline': [{'type': 'Rearrange',
                                                      'keys': ['frames'],
                                                      'ops': 'b n c (t1 t) h w -> (b t1) n c t h w',
                                                      't1': 24}],
                         'post_processing_pipeline': [{'type': 'Reduce',
                                                       'keys': ['feats'],
                                                       'ops': 'b n c t h w -> b c t',
                                                       'reduction': 'mean'},
                                                      {'type': 'Rearrange',
                                                       'keys': ['feats'],
                                                       'ops': '(b t1) c t -> b c (t1 t)',
                                                       't1': 24},
                                                      {'type': 'Interpolate',
                                                       'keys': ['feats'],
                                                       'size': 384}],
                         'norm_eval': False,
                         'freeze_backbone': False}},
 'projection': {'in_channels': 384,
                'out_channels': 512,
                'max_seq_len': 384,
                'attn_cfg': {'n_mha_win_size': -1}},
 'rpn_head': {'in_channels': 512,
              'feat_channels': 512,
              'physical_grid_actionformer': {'enabled': False,
                                             'required': False,
                                             'strict': True,
                                             'positions_key': 'irregular_selected_positions',
                                             'selected_count_keys': ('selected_valid_len',
                                                                     'irregular_selected_count'),
                                             'dense_valid_len_key': 'irregular_selected_valid_len'}},
 'native_temporal_geometry': {'enabled': True,
                              'tubelet_size': 2,
                              'expected_raw_count': 384,
                              'expected_token_count': 384,
                              'expected_transformer_depth': 12,
                              'expected_adapter_indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
                              'expected_adapter_kernel_size': 3,
                              'expected_adapter_dilation': 1}}

solver = {'train': {'batch_size': 2, 'num_workers': 2},
 'val': {'batch_size': 2, 'num_workers': 2},
 'test': {'batch_size': 2, 'num_workers': 2},
 'clip_grad_norm': 1,
 'amp': True,
 'fp16_compress': True,
 'static_graph': False,
 'ema': True}

scheduler = {'type': 'LinearWarmupCosineAnnealingLR', 'warmup_epoch': 5, 'max_epoch': 60}

workflow = {'logging_interval': 50,
 'checkpoint_interval': 5,
 'val_loss_interval': -1,
 'val_eval_interval': 0,
 'val_start_epoch': 60,
 'end_epoch': 60,
 'max_train_iters': 100}

inference = {'load_from_raw_predictions': False, 'save_raw_prediction': True}

post_processing = {'nms': {'use_soft_nms': True, 'sigma': 0.7, 'max_seg_num': 2000, 'multiclass': True, 'voting_thresh': 0.7},
 'save_dict': True}

work_dir = 'exps/thumos/adatad/duca_unified_fullmatrix/DUCA-UNIFIED-FULLMATRIX-v001-20260902/development_a11_seed3407'
