#!/usr/bin/env bash

[[ -n "${BASE:-}" ]] || {
  echo "[DUCA_P0_ENV][FAIL] BASE must be set before sourcing the canonical environment" >&2
  return 1 2>/dev/null || exit 1
}

export BASE
export PYTHON="${BASE}/conda_envs/opentad/bin/python"
export ADATAD_PRETRAIN_PATH="${BASE}/pretrained/vit-small-p16_videomae-k400-pre_16x4x1_kinetics-400_my.pth"
export YUZIBO_ROOT="${BASE}"
export C3_OFFICIAL_ACTION_SEG_REPOS="${BASE}/projects/external_official_action_segmentation_repos_20260702"
export THUMOS14_ANNOTATION_PATH="${BASE}/thumos14/annotations/thumos_14_anno.json"
export THUMOS14_CLASS_MAP="${BASE}/thumos14/annotations/category_idx.txt"
export THUMOS14_TRAIN_DATA_PATH="${BASE}/thumos14/train"
export THUMOS14_TEST_DATA_PATH="${BASE}/thumos14/test"

export DUCA_ONLINE_BUDGET=384
export DUCA_OFFICIAL_ADATAD_BUDGET=384
export DUCA_ONLINE_DENSE_WINDOW_SIZE=768
export DUCA_STRICT_CLAIM_MAX_BUDGET=384
export DUCA_VALIDATOR_MAX_BUDGET=384
export DUCA_BUDGET_CURVE_MODE=0
export DUCA_OFFICIAL_ADATAD_END_EPOCH=132
export DUCA_LOSS_SCHEDULE_STEPS_PER_EPOCH=100
export DUCA_LOSS_SCHEDULE_TOTAL_STEPS=13200
export DUCA_LOSS_SCHEDULE_WARMUP_FRACTION=0.05
export DUCA_LOSS_SCHEDULE_TRANSITION_FRACTION=0.15
export DUCA_LOSS_SCHEDULE_WARMUP_STEPS=660
export DUCA_LOSS_SCHEDULE_TRANSITION_STEPS=1980
export DUCA_LOSS_SCHEDULE_SHAPE=cosine
export DUCA_PROFILE_RUNTIME=0
export DUCA_PROFILE_SYNC_CUDA=1

export DUCA_COARSE_PROBE_MODEL=official-action-seg
export DUCA_COARSE_TCN_VARIANT=official_asformer
export DUCA_COARSE_OFFICIAL_BACKEND=official_asformer
export DUCA_COARSE_SPATIAL_SIZE=64
export DUCA_COARSE_HIDDEN_DIM=96
export DUCA_COARSE_PROBE_CHECKPOINT=
export DUCA_COARSE_REQUIRE_CHECKPOINT=0
export DUCA_COARSE_FROZEN=0
export DUCA_COARSE_SOURCE_NAME=online_c3_official_asformer_coarse_actionness

export DUCA_SELECTOR_ACTIONNESS_WEIGHT=0.05
export DUCA_SELECTOR_TRANSITION_WEIGHT=1.0
export DUCA_SELECTOR_UNCERTAINTY_WEIGHT=0.25
export DUCA_SELECTOR_UTILITY_WEIGHT=0.50
export DUCA_SELECTOR_BOUNDARY_WEIGHT=1.0
export DUCA_MAX_UNSELECTED_HOLE=15
export DUCA_STRUCTURED_TEMPERATURE=0.7

export DUCA_LOSS_ACTIONNESS_START=0.25
export DUCA_LOSS_ACTIONNESS_END=0.05
export DUCA_LOSS_BOUNDARY_START=0.50
export DUCA_LOSS_BOUNDARY_END=1.0
export DUCA_LOSS_START_ENDPOINT_START=0.50
export DUCA_LOSS_END_ENDPOINT_START=0.50
export DUCA_LOSS_CONTEXT_START=0.10
export DUCA_LOSS_DETECTOR_GRADIENT_START=0.0
export DUCA_LOSS_DETECTOR_UTILITY_END=0.10
export DUCA_LOSS_MAX_GAP_HOLE_END=0.25
export DUCA_LOSS_HOLE_END=0.0

export DUCA_OFFICIAL_ADATAD_CHECKPOINT_INTERVAL=5
export DUCA_OFFICIAL_ADATAD_VAL_INTERVAL=5
export DUCA_OFFICIAL_ADATAD_VAL_START_EPOCH=47

DUCA_P0_CANONICAL_ENV_KEYS=(
  ADATAD_PRETRAIN_PATH
  BASE
  C3_OFFICIAL_ACTION_SEG_REPOS
  DUCA_BUDGET_CURVE_MODE
  DUCA_COARSE_FROZEN
  DUCA_COARSE_HIDDEN_DIM
  DUCA_COARSE_OFFICIAL_BACKEND
  DUCA_COARSE_PROBE_CHECKPOINT
  DUCA_COARSE_PROBE_MODEL
  DUCA_COARSE_REQUIRE_CHECKPOINT
  DUCA_COARSE_SOURCE_NAME
  DUCA_COARSE_SPATIAL_SIZE
  DUCA_COARSE_TCN_VARIANT
  DUCA_LOSS_ACTIONNESS_END
  DUCA_LOSS_ACTIONNESS_START
  DUCA_LOSS_BOUNDARY_END
  DUCA_LOSS_BOUNDARY_START
  DUCA_LOSS_CONTEXT_START
  DUCA_LOSS_DETECTOR_GRADIENT_START
  DUCA_LOSS_DETECTOR_UTILITY_END
  DUCA_LOSS_END_ENDPOINT_START
  DUCA_LOSS_HOLE_END
  DUCA_LOSS_MAX_GAP_HOLE_END
  DUCA_LOSS_SCHEDULE_SHAPE
  DUCA_LOSS_SCHEDULE_STEPS_PER_EPOCH
  DUCA_LOSS_SCHEDULE_TOTAL_STEPS
  DUCA_LOSS_SCHEDULE_TRANSITION_FRACTION
  DUCA_LOSS_SCHEDULE_TRANSITION_STEPS
  DUCA_LOSS_SCHEDULE_WARMUP_FRACTION
  DUCA_LOSS_SCHEDULE_WARMUP_STEPS
  DUCA_LOSS_START_ENDPOINT_START
  DUCA_MAX_UNSELECTED_HOLE
  DUCA_OFFICIAL_ADATAD_BUDGET
  DUCA_OFFICIAL_ADATAD_CHECKPOINT_INTERVAL
  DUCA_OFFICIAL_ADATAD_END_EPOCH
  DUCA_OFFICIAL_ADATAD_VAL_INTERVAL
  DUCA_OFFICIAL_ADATAD_VAL_START_EPOCH
  DUCA_ONLINE_BUDGET
  DUCA_ONLINE_DENSE_WINDOW_SIZE
  DUCA_PROFILE_RUNTIME
  DUCA_PROFILE_SYNC_CUDA
  DUCA_SELECTOR_ACTIONNESS_WEIGHT
  DUCA_SELECTOR_BOUNDARY_WEIGHT
  DUCA_SELECTOR_TRANSITION_WEIGHT
  DUCA_SELECTOR_UNCERTAINTY_WEIGHT
  DUCA_SELECTOR_UTILITY_WEIGHT
  DUCA_STRICT_CLAIM_MAX_BUDGET
  DUCA_STRUCTURED_TEMPERATURE
  DUCA_VALIDATOR_MAX_BUDGET
  PYTHON
  THUMOS14_ANNOTATION_PATH
  THUMOS14_CLASS_MAP
  THUMOS14_TEST_DATA_PATH
  THUMOS14_TRAIN_DATA_PATH
  YUZIBO_ROOT
)

duca_p0_canonical_env_payload() {
  local key
  for key in "${DUCA_P0_CANONICAL_ENV_KEYS[@]}"; do
    printf '%s=%s\n' "${key}" "${!key}"
  done
}
