_base_ = ["./duca_transition_only_fixed384_official_adatad_backend_full_train.py"]

import os


duca_transition_only_contract = dict(
    _delete_=True,
    route="DUCA_LOCAL_CELL_COUNTERFACTUAL_FIXED384",
    stage="implemented_pending_focused_tests_and_real_cuda_gate",
    task="offline_temporal_action_detection",
    online_tad=False,
    streaming=False,
    full_window_selector=True,
    pre_backbone_plugin=True,
    main_method_candidate=True,
    empirically_supported=False,
    paper_claim_allowed=False,
    metric_claim_allowed=False,
    official_adatad_backend=True,
    official_backend_semantics="official_components_with_duca_wrapper_not_source_identical",
    detector_head_type="ActionFormerHead",
    detector_head_changed=False,
    detector_loss_changed=False,
    detector_nms_changed=False,
    selector_variant="transition_only",
    coarse_probe="official_asformer_binary_actionness",
    coarse_hidden_kind="official_asformer_encoder_hidden",
    coarse_probe_joint_trainable=True,
    actionness_role="binary_coarse_classification_only",
    transition_role="indirect_boundary_localization_and_within_cell_frame_utility",
    acquisition_policy="local_cell_deformation",
    hard_soft_feasible_family="one_frame_per_exact_uniform_voronoi_cell",
    hard_tie_break="exact_uniform_anchor",
    exact_budget=384,
    dense_window_size=768,
    derived_max_unselected_hole=3,
    posthoc_hard_repair=False,
    policy_homotopy="disabled",
    global_viterbi="disabled",
    global_gram_proximal="disabled",
    detector_gradient_bridge="disabled",
    detector_gradient_final_weight=0.0,
    detector_utility_learning="train_only_detached_distinct_local_cell_hard_flip",
    detector_utility_loss="weighted_signed_logistic_on_add_minus_remove_score",
    detector_utility_is_direct_gradient=False,
    counterfactual_teacher_producer_integrated=True,
    counterfactual_teacher_detector_objective="official_actionformer_cls_plus_reg",
    counterfactual_teacher_max_candidates=4,
    counterfactual_teacher_inference_passes=0,
    deployment_allowed=False,
    no_ledger_decision=True,
    forbid_external_actionness=True,
    forbid_raw_prediction_cache=True,
    teacher_free_eval=True,
)


model = dict(
    frame_selector=dict(
        _delete_=True,
        type="DucaOnlineFrameSelector",
        in_channels=3,
        dense_window_size=768,
        budget=384,
        budget_mode="fixed",
        max_radius=0,
        acquisition_policy="local_cell_deformation",
        structured_temperature=0.7,
        local_cell_force_exact_uniform=False,
        inference_policy_alpha=1.0,
        selector_variant="transition_only",
        selector_hidden_channels=64,
        coarse_trunk_lr=2.5e-5,
        action_head_lr=5.0e-5,
        transition_scorer_lr=1.0e-4,
        coarse_hidden_dim=96,
        use_coarse_hidden_features=True,
        require_coarse_hidden_features=True,
        max_unselected_hole=None,
        max_gap_loss_max_unselected_hole=None,
        soft_max_gap_loss_enabled=False,
        transition_target_sigma=2.0,
        transition_target_radius=4,
        transition_boundary_radius=4,
        transition_distribution_temperature=0.7,
        hard_max_gap_repair=False,
        fail_on_infeasible_max_gap=True,
        actionness_weight=0.0,
        transition_weight=0.0,
        uncertainty_weight=0.0,
        utility_weight=0.0,
        boundary_weight=0.0,
        detector_gradient_mode="none",
        counterfactual_objective="local_cell_signed_logistic",
        counterfactual_utility_distillation_weight=0.25,
        counterfactual_utility_temperature=0.7,
        counterfactual_max_candidates=4,
        require_counterfactual_utility_teacher=True,
        coordinate_space="original_time",
        detector_output_coordinate_space="selected_axis_index",
        selected_positions_unit="original_time_index",
        loss_weights=dict(
            actionness=1.0,
            detector=1.0,
            transition=0.5,
            transition_boundary=0.25,
            max_gap_hole=0.0,
            teacher=0.0,
            detector_utility=0.0,
            start=0.0,
            end=0.0,
            context=0.0,
            boundary=0.0,
            hole=0.0,
            budget=0.0,
            redundancy=0.0,
            radius=0.0,
            entropy=0.0,
        ),
        loss_weight_schedule=dict(
            type="progressive_joint",
            shape="cosine",
            warmup_steps=0,
            transition_steps=1,
            actionness=dict(start=1.0, end=1.0),
            transition=dict(start=0.5, end=0.5),
            transition_boundary=dict(start=0.25, end=0.25),
            detector_gradient=dict(
                start=0.0,
                end=0.0,
                warmup_steps=0,
                transition_steps=0,
            ),
        ),
        no_ledger_decision=True,
        remap_gt_to_selected_axis=True,
        selected_axis_remap_required=True,
        forbid_ledger=True,
        forbid_raw_prediction_cache=True,
        forbid_external_actionness=True,
        require_external_actionness=False,
        profile_runtime=os.environ.get("DUCA_PROFILE_RUNTIME", "0") == "1",
        profile_sync_cuda=os.environ.get("DUCA_PROFILE_SYNC_CUDA", "1") != "0",
        actionness_source_cfg=dict(
            type="C3CoarseProbeActionnessSource",
            source_name="shared_official_asformer_binary_actionness",
            probe_model="official-action-seg",
            official_action_seg_backend="official_asformer",
            spatial_size=64,
            tcn_hidden_dim=96,
            official_num_layers=2,
            return_hidden_features=True,
            require_hidden_features=True,
            hidden_output_kind="official_asformer_encoder_hidden",
            checkpoint_path="",
            require_checkpoint=False,
            frozen=False,
            trainable=True,
            thumos_trained=True,
            uses_labels=True,
            uses_teacher=False,
            uses_gt=True,
            uses_prediction_cache=False,
            trained_with_thumos_labels=True,
            trained_with_gt_segments=True,
            training_dataset="THUMOS14",
            training_supervision_scope="train_only",
            uses_labels_at_inference=False,
            uses_gt_at_inference=False,
            uses_teacher_at_inference=False,
            uses_prediction_cache_at_inference=False,
            calibration_split="none",
            calibration_temperature=1.0,
            calibration_bias=0.0,
        ),
    ),
)


workflow = dict(formal_protocol="duca_cellcf_v1")


work_dir = "exps/thumos/adatad/duca_cellcf_fixed384_official_adatad_backend_full_train"
