_base_ = ["./duca_paper_full200_base.py"]


candidate_budgets = (192, 256, 384, 512)
candidate_costs = tuple(float(value) for value in candidate_budgets)

model = dict(
    frame_selector=dict(
        _delete_=True,
        type="DucaRimeFrameSelector",
        in_channels=3,
        rime_arm="fixed_bound",
        candidate_budgets=candidate_budgets,
        candidate_costs=candidate_costs,
        fixed_budget=384,
        dense_window_size=768,
        frozen_price=0.0,
        target_mean_cost=384.0,
        risk_weight=1.0,
        risk_threshold=0.35,
        uncertainty_z=1.645,
        decoder_family="independent",
        weak_overlap_fraction=0.50,
        controller_hidden_dim=128,
        execution_quantum=16,
        require_frozen_protocol=False,
        coarse_hidden_dim=96,
        selector_hidden_dim=64,
        coverage_floor_weight=0.10,
        score_temperature=0.70,
        path_temperature=1.0,
        transition_target_sigma=2.0,
        transition_target_radius=4,
        transition_boundary_radius=4,
        transition_distribution_temperature=0.70,
        action_loss_weight=1.0,
        transition_loss_weight=0.50,
        transition_boundary_loss_weight=0.25,
        budget_utility_loss_weight=1.0,
        budget_risk_loss_weight=1.0,
        budget_uncertainty_loss_weight=0.25,
        rank_alignment_loss_weight=0.0,
        coarse_trunk_lr=2.5e-5,
        action_head_lr=5.0e-5,
        selector_lr=1.0e-4,
        detector_bridge_gradient_scale=1.0,
        detector_coordinate_mode="selected_axis_plugin",
        strict_physical_metadata=True,
        forbid_raw_prediction_cache=True,
        actionness_source_cfg=dict(
            type="C3CoarseProbeActionnessSource",
            source_name="duca_paper_joint_asformer_binary_actionness",
            probe_model="official-action-seg",
            official_action_seg_backend="official_asformer",
            spatial_size=64,
            tcn_hidden_dim=96,
            official_num_layers=2,
            dropout=0.0,
            return_hidden_features=True,
            require_hidden_features=True,
            hidden_output_kind="official_asformer_encoder_hidden",
            policy_hidden_gradient_scope="none",
            checkpoint_path="",
            require_checkpoint=False,
            frozen=False,
            trainable=True,
            train_split_supervised=True,
            calibration_split="none",
            calibration_temperature=1.0,
            calibration_bias=0.0,
            thumos_trained=True,
            uses_labels=True,
            uses_teacher=False,
            uses_gt=True,
            uses_prediction_cache=False,
            trained_with_thumos_labels=True,
            trained_with_gt_segments=True,
            training_dataset="THUMOS14",
            training_supervision_scope="train_only",
        ),
    ),
    backbone=dict(
        backbone=dict(total_frames=512, with_cp=False),
        custom=dict(
            dynamic_temporal_bucket=True,
            dynamic_temporal_clip_len=16,
        ),
    ),
    projection=dict(max_seq_len=512),
    rpn_head=dict(physical_grid_actionformer=None),
)

duca_rime_contract = dict(
    task="offline_temporal_action_detection",
    online_tad=False,
    streaming=False,
    pre_backbone_plugin=True,
    detector_coordinate_mode="selected_axis_plugin",
    inverse_map_before_official_nms=True,
    detector_head_modified=False,
    candidate_budgets=candidate_budgets,
    pad_to_kmax=False,
    execution_quantum=16,
    official_final_subset_consumed=False,
    empirically_supported=False,
    paper_ready=False,
)

work_dir = "exps/thumos/adatad/duca_paper_rime_base_do_not_run"

del candidate_costs
