_base_ = ["./duca_transition_only_fixed384_official_adatad_backend_full_train.py"]


duca_trainfree_contract = dict(
    task="offline_temporal_action_detection",
    target_dataset_training=False,
    target_dataset_calibration=False,
    selector_optimization=False,
    frozen_external_pretraining=True,
    exact_budget=384,
    dense_window_size=768,
    max_unselected_hole=2,
    detector_backend="official_derived_adatad_actionformer",
    complete_encoder_cost_required=True,
    paper_claim_allowed=False,
)


duca_transition_only_contract = dict(
    _delete_=True,
    route="DUCA_TARGET_TRAIN_FREE_FIXED384_OFFICIAL60",
    stage="frozen_prior_parameter_free_selector_detector_training",
    task="offline_temporal_action_detection",
    online_tad=False,
    streaming=False,
    pre_backbone_plugin=True,
    selector_variant="direct_boundary_parameter_free",
    target_dataset_frontend_training=False,
    target_dataset_frontend_calibration=False,
    inference_gt_free=True,
    inference_teacher_free=True,
    inference_cache_free=True,
    exact_budget=384,
    max_unselected_hole=2,
    detector_gradient_updates="detector_only",
    paper_claim_allowed=False,
)


model = dict(
    selector_train_only=False,
    selector_train_only_skip_detector=False,
    frame_selector=dict(
        _delete_=True,
        type="DucaOnlineFrameSelector",
        in_channels=3,
        dense_window_size=768,
        budget=384,
        budget_mode="fixed",
        max_radius=0,
        acquisition_policy="global_structured_topk",
        structured_temperature=0.7,
        inference_policy_alpha=1.0,
        selector_variant="direct_boundary",
        parameter_free_selector=True,
        selector_hidden_channels=0,
        use_coarse_hidden_features=False,
        require_coarse_hidden_features=False,
        max_unselected_hole=2,
        max_gap_loss_max_unselected_hole=2,
        soft_max_gap_loss_enabled=False,
        transition_objective="gaussian_mass",
        transition_boundary_radius=2,
        hard_max_gap_repair=False,
        fail_on_infeasible_max_gap=True,
        actionness_weight=0.0,
        transition_weight=0.0,
        uncertainty_weight=0.0,
        utility_weight=0.0,
        boundary_weight=0.0,
        detector_gradient_mode="none",
        counterfactual_utility_distillation_weight=0.0,
        require_counterfactual_utility_teacher=False,
        coordinate_space="original_time",
        detector_output_coordinate_space="selected_axis_index",
        selected_positions_unit="original_time_index",
        loss_weights=dict(
            actionness=0.0,
            detector=1.0,
            transition=0.0,
            transition_boundary=0.0,
            max_gap_hole=0.0,
            teacher=0.0,
            detector_utility=0.0,
            start=0.0,
            end=0.0,
            context=0.0,
            boundary=0.0,
            hole=0.0,
            budget=0.0,
            redundancy=0.0,
            radius=0.0,
            entropy=0.0,
        ),
        loss_weight_schedule=dict(
            type="progressive_joint",
            shape="cosine",
            warmup_steps=0,
            transition_steps=1,
            actionness=dict(start=0.0, end=0.0),
            transition=dict(start=0.0, end=0.0),
            transition_boundary=dict(start=0.0, end=0.0),
            detector_gradient=dict(start=0.0, end=0.0),
            policy_alpha=dict(start=1.0, end=1.0),
        ),
        no_ledger_decision=True,
        remap_gt_to_selected_axis=True,
        selected_axis_remap_required=True,
        forbid_ledger=True,
        forbid_raw_prediction_cache=True,
        forbid_external_actionness=True,
        require_external_actionness=False,
        profile_runtime=True,
        profile_sync_cuda=True,
        actionness_source_cfg=dict(
            type="C3CoarseProbeActionnessSource",
            source_name="frozen_imagenet_mobilenetv3_feature_change",
            probe_model="mobilenetv3",
            spatial_size=64,
            mobilenet_pretrained=True,
            mobilenet_variant="small",
            mobilenet_freeze_backbone=True,
            mobilenet_preserve_pretrained_classifier=True,
            temporal_probe_stride=4,
            temporal_interpolation_mode="hidden_linear",
            train_free_evidence_mode="frozen_feature_change",
            return_hidden_features=True,
            require_hidden_features=True,
            checkpoint_path="",
            require_checkpoint=False,
            frozen=True,
            trainable=False,
            train_split_supervised=False,
            thumos_trained=False,
            uses_labels=False,
            uses_teacher=False,
            uses_gt=False,
            uses_prediction_cache=False,
            trained_with_thumos_labels=False,
            trained_with_gt_segments=False,
            training_dataset="ImageNet-1K",
            training_supervision_scope="external_pretraining_only",
            calibration_split="none",
        ),
    ),
)


work_dir = "exps/thumos/adatad/duca_trainfree_mobilenet_feature_change_fixed384_official60"
