#!/usr/bin/env bash
# Continue a DUCA Evidence Recovery DAG after a QOS submission deferral.
source /etc/profile 2>/dev/null || true
set -euo pipefail

MANIFEST="${1:?usage: $0 /path/to/dag_state.env [max_active_jobs]}"
MAX_ALLOWED="${2:-${MAX_ALLOWED:-8}}"
if [[ ! -f "${MANIFEST}" ]]; then
  echo "[ERROR] DAG manifest not found: ${MANIFEST}" >&2
  exit 2
fi
if [[ ! "${MAX_ALLOWED}" =~ ^[0-9]+$ ]] || (( MAX_ALLOWED < 1 )); then
  echo "[ERROR] MAX_ALLOWED must be a positive integer: ${MAX_ALLOWED}" >&2
  exit 2
fi

# A heartbeat and a manual recovery command may inspect the same manifest.
exec 9>"${MANIFEST}.lock"
if ! flock -n 9; then
  echo "[WAIT] Another continuation already owns ${MANIFEST}.lock"
  exit 0
fi

# Manifests are generated by the submission wrappers and contain only shell
# assignments needed to reconstruct this DAG.
source "${MANIFEST}"
: "${RUN_ROOT:?RUN_ROOT missing from manifest}"
: "${REPO_ROOT:?REPO_ROOT missing from manifest}"
: "${YUZIBO_ROOT:?YUZIBO_ROOT missing from manifest}"
: "${DUCA_VIDEOMAE_PRETRAIN:?DUCA_VIDEOMAE_PRETRAIN missing from manifest}"
: "${DUCA_SEEDS:?DUCA_SEEDS missing from manifest}"
: "${ARRAY_MAX:?ARRAY_MAX missing from manifest}"
: "${TRAIN_JOB_ID:?TRAIN_JOB_ID missing from manifest}"
COST_JOB_ID="${COST_JOB_ID:-}"

SLURM_USER="${DUCA_SLURM_USER:-sczc063}"
DUCA_H65_LEDGER_ROOT="${DUCA_H65_LEDGER_ROOT:-${YUZIBO_ROOT}/projects/c3_lowres_action_probe/ledger_exports/c3_official_asformer_delta_ledgers_20260702_052357_+0800}"
DUCA_H65_TRAIN_LEDGER_PATH="${DUCA_H65_TRAIN_LEDGER_PATH:-${DUCA_H65_LEDGER_ROOT}/train/value_transport_ledger_delta_p_action_384.jsonl}"
DUCA_H65_VAL_LEDGER_PATH="${DUCA_H65_VAL_LEDGER_PATH:-${DUCA_H65_LEDGER_ROOT}/val/value_transport_ledger_delta_p_action_384.jsonl}"
DUCA_H65_TEST_LEDGER_PATH="${DUCA_H65_TEST_LEDGER_PATH:-${DUCA_H65_LEDGER_ROOT}/test/value_transport_ledger_delta_p_action_384.jsonl}"
mkdir -p "${RUN_ROOT}/slurm_logs"

log() {
  printf '[%s] %s\n' "$(date +'%Y-%m-%d %H:%M:%S')" "$*"
}

job_active() {
  local job_id="$1"
  [[ -n "${job_id}" ]] && squeue -h -j "${job_id}" 2>/dev/null | grep -q .
}

job_phase() {
  local job_id="$1"
  local raw
  if job_active "${job_id}"; then
    printf 'ACTIVE\n'
    return 0
  fi
  raw="$(sacct -X -n -P -o State -j "${job_id}" 2>/dev/null | sed '/^[[:space:]]*$/d;s/+.*//')"
  if [[ -z "${raw}" ]]; then
    printf 'UNKNOWN\n'
  elif grep -Eq '^(FAILED|CANCELLED|TIMEOUT|OUT_OF_MEMORY|NODE_FAIL|PREEMPTED|BOOT_FAIL|DEADLINE|REVOKED|SPECIAL_EXIT|DEADLINE)' <<<"${raw}"; then
    printf 'FAILED\n'
  elif grep -Eq '^(PENDING|RUNNING|CONFIGURING|COMPLETING|SUSPENDED)' <<<"${raw}"; then
    printf 'ACTIVE\n'
  elif grep -q '^COMPLETED$' <<<"${raw}"; then
    printf 'COMPLETED\n'
  else
    printf 'UNKNOWN\n'
  fi
}

failed_array_indices() {
  local job_id="$1"
  sacct -X -n -P -j "${job_id}" --format=JobID,State 2>/dev/null \
    | awk -F'|' '
        $2 ~ /^(FAILED|CANCELLED|TIMEOUT|OUT_OF_MEMORY|NODE_FAIL|PREEMPTED|BOOT_FAIL|DEADLINE|REVOKED|SPECIAL_EXIT)/ \
          && $1 ~ /^[0-9]+_[0-9]+$/ {
            sub(/^.*_/, "", $1)
            print $1
          }
      ' \
    | sort -n | uniq | paste -sd, -
}

active_count() {
  squeue -u "${SLURM_USER}" -h 2>/dev/null | wc -l | tr -d ' '
}

is_qos_limit() {
  [[ "$1" == *AssocMaxSubmitJobLimit* || "$1" == *QOS* || "$1" == *job.submit.limit* ]]
}

write_manifest() {
  local state="$1"
  local tmp="${MANIFEST}.tmp.$$"
  {
    printf 'STATE=%q\n' "${state}"
    printf 'RUN_ROOT=%q\n' "${RUN_ROOT}"
    printf 'REPO_ROOT=%q\n' "${REPO_ROOT}"
    printf 'YUZIBO_ROOT=%q\n' "${YUZIBO_ROOT}"
    printf 'DUCA_VIDEOMAE_PRETRAIN=%q\n' "${DUCA_VIDEOMAE_PRETRAIN}"
    printf 'DUCA_H65_LEDGER_ROOT=%q\n' "${DUCA_H65_LEDGER_ROOT}"
    printf 'DUCA_H65_TRAIN_LEDGER_PATH=%q\n' "${DUCA_H65_TRAIN_LEDGER_PATH}"
    printf 'DUCA_H65_VAL_LEDGER_PATH=%q\n' "${DUCA_H65_VAL_LEDGER_PATH}"
    printf 'DUCA_H65_TEST_LEDGER_PATH=%q\n' "${DUCA_H65_TEST_LEDGER_PATH}"
    printf 'DUCA_SEEDS=%q\n' "${DUCA_SEEDS}"
    printf 'ARRAY_MAX=%q\n' "${ARRAY_MAX}"
    printf 'COST_JOB_ID=%q\n' "${COST_JOB_ID}"
    printf 'TRAIN_JOB_ID=%q\n' "${TRAIN_JOB_ID}"
    printf 'EVAL_JOB_ID=%q\n' "${EVAL_JOB_ID:-}"
    printf 'STATS_JOB_ID=%q\n' "${STATS_JOB_ID:-}"
  } > "${tmp}"
  mv -f "${tmp}" "${MANIFEST}"
}

submit_eval() {
  local output
  if output="$(sbatch --parsable \
      --dependency="afterok:${TRAIN_JOB_ID}" \
      --array="0-${ARRAY_MAX}" \
      --output="${RUN_ROOT}/slurm_logs/%x_%A_%a.out" \
      --error="${RUN_ROOT}/slurm_logs/%x_%A_%a.err" \
      --export=ALL,DUCA_RUN_ROOT="${RUN_ROOT}",DUCA_SEEDS="${DUCA_SEEDS}",DUCA_REPO_ROOT="${REPO_ROOT}",YUZIBO_ROOT="${YUZIBO_ROOT}",DUCA_VIDEOMAE_PRETRAIN="${DUCA_VIDEOMAE_PRETRAIN}",DUCA_H65_LEDGER_ROOT="${DUCA_H65_LEDGER_ROOT}",DUCA_H65_TRAIN_LEDGER_PATH="${DUCA_H65_TRAIN_LEDGER_PATH}",DUCA_H65_VAL_LEDGER_PATH="${DUCA_H65_VAL_LEDGER_PATH}",DUCA_H65_TEST_LEDGER_PATH="${DUCA_H65_TEST_LEDGER_PATH}" \
      "${REPO_ROOT}/scripts/run_duca_evidence_recovery_eval_array_n16r4.sbatch" 2>&1)"; then
    EVAL_JOB_ID="${output}"
    write_manifest "EVAL_SUBMITTED"
    log "[SUCCESS] Evaluation array submitted: ${EVAL_JOB_ID}"
    return 0
  fi
  if is_qos_limit "${output}"; then
    write_manifest "EVAL_DEFERRED"
    log "[DEFERRED] Evaluation submission is still limited by Slurm QOS: ${output}"
    return 0
  fi
  write_manifest "EVAL_SUBMIT_FAILED"
  log "[ERROR] Evaluation submission failed: ${output}"
  return 1
}

submit_failed_training_cells() {
  local failed_indices="$1"
  local output
  if [[ -z "${failed_indices}" ]]; then
    log "[ERROR] Training array ${TRAIN_JOB_ID} failed but no failed task indices were readable."
    return 1
  fi
  if output="$(sbatch --parsable \
      --array="${failed_indices}" \
      --output="${RUN_ROOT}/slurm_logs/%x_%A_%a.out" \
      --error="${RUN_ROOT}/slurm_logs/%x_%A_%a.err" \
      --export=ALL,DUCA_RUN_ROOT="${RUN_ROOT}",DUCA_SEEDS="${DUCA_SEEDS}",DUCA_REPO_ROOT="${REPO_ROOT}",YUZIBO_ROOT="${YUZIBO_ROOT}",DUCA_VIDEOMAE_PRETRAIN="${DUCA_VIDEOMAE_PRETRAIN}",DUCA_H65_LEDGER_ROOT="${DUCA_H65_LEDGER_ROOT}",DUCA_H65_TRAIN_LEDGER_PATH="${DUCA_H65_TRAIN_LEDGER_PATH}",DUCA_H65_VAL_LEDGER_PATH="${DUCA_H65_VAL_LEDGER_PATH}",DUCA_H65_TEST_LEDGER_PATH="${DUCA_H65_TEST_LEDGER_PATH}" \
      "${REPO_ROOT}/scripts/run_duca_evidence_recovery_train_array_n16r4.sbatch" 2>&1)"; then
    TRAIN_JOB_ID="${output}"
    write_manifest "TRAIN_SUBMITTED"
    log "[RETRY] Resubmitted failed training cells indices=${failed_indices} as array ${TRAIN_JOB_ID}."
    return 0
  fi
  log "[ERROR] Failed-cell training resubmission failed for indices=${failed_indices}: ${output}"
  return 1
}

submit_stats() {
  local output
  if output="$(sbatch --parsable \
      --dependency="afterok:${EVAL_JOB_ID}" \
      --output="${RUN_ROOT}/slurm_logs/%x_%j.out" \
      --error="${RUN_ROOT}/slurm_logs/%x_%j.err" \
      --export=ALL,DUCA_RUN_ROOT="${RUN_ROOT}",DUCA_SEEDS="${DUCA_SEEDS}",DUCA_REPO_ROOT="${REPO_ROOT}",YUZIBO_ROOT="${YUZIBO_ROOT}",DUCA_VIDEOMAE_PRETRAIN="${DUCA_VIDEOMAE_PRETRAIN}",DUCA_H65_LEDGER_ROOT="${DUCA_H65_LEDGER_ROOT}",DUCA_H65_TRAIN_LEDGER_PATH="${DUCA_H65_TRAIN_LEDGER_PATH}",DUCA_H65_VAL_LEDGER_PATH="${DUCA_H65_VAL_LEDGER_PATH}",DUCA_H65_TEST_LEDGER_PATH="${DUCA_H65_TEST_LEDGER_PATH}" \
      "${REPO_ROOT}/scripts/run_duca_evidence_recovery_stats_n16r4.sbatch" 2>&1)"; then
    STATS_JOB_ID="${output}"
    write_manifest "SUBMITTED"
    log "[SUCCESS] Statistical analysis submitted: ${STATS_JOB_ID}"
    return 0
  fi
  if is_qos_limit "${output}"; then
    write_manifest "STATS_DEFERRED"
    log "[DEFERRED] Statistics submission is still limited by Slurm QOS: ${output}"
    return 0
  fi
  write_manifest "STATS_SUBMIT_FAILED"
  log "[ERROR] Statistics submission failed: ${output}"
  return 1
}

STATE="${STATE:-TRAIN_SUBMITTED}"
if [[ -n "${STATS_JOB_ID:-}" ]]; then
  STATS_PHASE="$(job_phase "${STATS_JOB_ID}")"
  case "${STATS_PHASE}" in
    COMPLETED)
      write_manifest "COMPLETE"
      log "[DONE] Statistics job ${STATS_JOB_ID} completed; manifest marked COMPLETE."
      exit 0
      ;;
    FAILED)
      write_manifest "STATS_FAILED"
      log "[ERROR] Statistics job ${STATS_JOB_ID} failed; inspect its Slurm stderr."
      exit 1
      ;;
    UNKNOWN)
      write_manifest "STATS_UNKNOWN"
      log "[ERROR] Statistics job ${STATS_JOB_ID} has no readable Slurm accounting state."
      exit 1
      ;;
    *)
      log "[WAIT] Statistics job ${STATS_JOB_ID} is ${STATS_PHASE}; no continuation needed yet."
      exit 0
      ;;
  esac
fi

TRAIN_PHASE="$(job_phase "${TRAIN_JOB_ID}")"
if [[ "${TRAIN_PHASE}" == FAILED ]]; then
  failed_indices="$(failed_array_indices "${TRAIN_JOB_ID}")"
  if [[ -n "${failed_indices}" ]]; then
    submit_failed_training_cells "${failed_indices}"
    exit $?
  fi
  write_manifest "TRAIN_FAILED"
  log "[ERROR] Training array ${TRAIN_JOB_ID} failed; inspect per-task Slurm stderr before retrying."
  exit 1
elif [[ "${TRAIN_PHASE}" == UNKNOWN ]]; then
  write_manifest "TRAIN_UNKNOWN"
  log "[ERROR] Training array ${TRAIN_JOB_ID} has no readable Slurm accounting state."
  exit 1
elif [[ "${TRAIN_PHASE}" != COMPLETED ]]; then
  log "[WAIT] Training array ${TRAIN_JOB_ID} is ${TRAIN_PHASE}; continuation deferred."
  exit 0
fi

if [[ -z "${EVAL_JOB_ID:-}" ]]; then
  active="$(active_count)"
  if (( active >= MAX_ALLOWED )); then
    log "[WAIT] Training completed, but active jobs=${active} >= MAX_ALLOWED=${MAX_ALLOWED}; evaluation deferred."
    exit 0
  fi
  submit_eval
  exit $?
fi

EVAL_PHASE="$(job_phase "${EVAL_JOB_ID}")"
if [[ "${EVAL_PHASE}" == FAILED ]]; then
  write_manifest "EVAL_FAILED"
  log "[ERROR] Evaluation array ${EVAL_JOB_ID} failed; inspect per-task Slurm stderr before retrying."
  exit 1
elif [[ "${EVAL_PHASE}" == UNKNOWN ]]; then
  write_manifest "EVAL_UNKNOWN"
  log "[ERROR] Evaluation array ${EVAL_JOB_ID} has no readable Slurm accounting state."
  exit 1
elif [[ "${EVAL_PHASE}" != COMPLETED ]]; then
  log "[WAIT] Evaluation array ${EVAL_JOB_ID} is ${EVAL_PHASE}; continuation deferred."
  exit 0
fi

active="$(active_count)"
if (( active >= MAX_ALLOWED )); then
  log "[WAIT] Evaluation completed, but active jobs=${active} >= MAX_ALLOWED=${MAX_ALLOWED}; statistics deferred."
  exit 0
fi
submit_stats
